### ISSUE TITLE
In rare cases, jdc and winds.mobi display different values

### ISSUE THREAD

**Issue by ysavary** [winds-mobi/winds-mobi-providers#1]
In this example, for the "Chalais" stations:

jdc:
``` 
{
"unix-time": 1565160000,
"wind-direction": 212,
"wind-average": 0.1,
"wind-maximum": 5.9,
"temperature": 17.5,
"humidity": 90
}
```

winds.mobi:
```
{
"_id": 1565160000,
"w-dir": 212,
"w-avg": 0.1,
"w-max": 29.4,
"temp": 17.5,
"hum": 90
}
```

An issue with this code?
https://github.com/winds-mobi/winds-mobi-providers/blob/ae4225c65dbe408f5b977cb9e858442069b49fa0/jdc/m2a.class.php#L687

@gemotech do you have an idea?

**Comment by gemotech** [comment]
No, it's just a case where maximum wind speed is too high compared to
average wind speed ! It happens sometimes when there isn't quite any wind.

So, I just found a solution to compute a new maximum value.
I don't have the calculation anymore, but it is on the website. I could
search for it.

Best regards,
Gerald


Le mer. 7 août 2019 à 12:42, Yann Savary <notifications@github.com> a
écrit :

**Comment by ysavary** [comment]
Hi @gemotech,

I would be nice if you can help me on this issue. A user complained today about this peak:

![Screen Shot 2019-08-26 at 19 17 21](https://user-images.githubusercontent.com/600094/63708995-2ec59280-c836-11e9-9792-847962084707.PNG)

which is not existing on jdc website:

![Screen Shot 2019-08-26 at 19 17 05](https://user-images.githubusercontent.com/600094/63709005-3422dd00-c836-11e9-9d3f-18cb5769b27d.PNG)

Thank you,
Yann
