### ISSUE TITLE
Station changed on Röti - Switzerland

### ISSUE THREAD

**Issue by ysavary** [winds-mobi/winds-mobi-providers#14]
Hi @McRender,

Regarding your issue: https://github.com/ysavary/WindMobile2-Server/issues/34. This repository was not used anymore, I have archived it.

Holfuy stations are automatically imported into winds.mobi. You have to enable the "third party access" and be sure that your Holfuy station has "paragliding" label. You can check that with the Holfuy admin web interface.

**Comment by McRender** [comment]
Thanks Yann

API access should be enabled and I also have set the paragliding label for this station. I hope this should be all.

**Comment by ysavary** [comment]
It looks like ok now: https://winds.mobi/stations/list/holfuy-1368
