### ISSUE TITLE
Api with borntofly return no data

### ISSUE THREAD

**Issue by libertykite** [winds-mobi/winds-mobi-providers#53]
Hi ,

The request : 
https://winds.mobi/api/2.2/stations/?limit=1000&provider=borntofly
return no data, dont know if is normal or not :-)

**Comment by ysavary** [comment]
Hi,

Please try with another provider: https://winds.mobi/api/2.2/stations/?limit=2&provider=holfuy

The only station of [borntofly.ch](https://github.com/winds-mobi/winds-mobi-providers/blob/main/providers/borntofly.py#L66) provider is no longer returning data since a long time.
