### ISSUE TITLE
sfl.ch data seems broken

### ISSUE THREAD

**Issue by MichalBryxi** [winds-mobi/winds-mobi-providers#55]
When you open weather stations from `slf.ch` [for example Mannlichen](https://winds.mobi/stations/map/slf-MAN1) you can see that last update was _4 days ago_:

![Screenshot 2023-02-05 at 18 56 47](https://user-images.githubusercontent.com/847473/216836943-17037ebc-a542-4e21-abd5-6e3df5d34d22.png)

I tried to find respective data on slf.ch and it _seems_ to be working ok: https://whiterisk.ch/en/snow/station/IMIS/MAN1?returnMeasurementParameter=WIND_MEAN.

So maybe change in their API? IDK.

**Comment by ysavary** [comment]
Hi @MichalBryxi,

Thanks for reporting this issue!

I fixed slf provider with their new public API in #56 

Please tell me if you discover issues with the new code.
