### ISSUE TITLE
Duplicate station

### ISSUE THREAD

**Issue by gereic** [winds-mobi/winds-mobi-providers#71]
@ysavary 
I had to change the station "ProBerg" (GXAircom).
The ID of the station is the hardware-serial, so If it gets changed (cause of defect board), it gets a new ID.
After changing, I saw, that of course, the old station is still visible, but has no data.

Does the station disappear after a time (1 week with no data) or so ?

Otherwise, can you please remove the id 08E440, I think that was the id of the old station.

**Comment by ysavary** [comment]
Yes, a station that is not publishing new measurements during 60 days will be removed from mongodb.

https://github.com/winds-mobi/winds-mobi-providers/blob/main/run_scheduler.py#L25

**Comment by gereic** [comment]
Thanks.

**Comment by ysavary** [comment]
@gereic 

I deleted the station `gxaircom-08E440` and its measurements collections manually.

You can see `gxaircom` stations only by using subdomain: https://gxaircom.winds.mobi/stations/map
