### ISSUE TITLE
gxaircom.net seems to be broken

### ISSUE THREAD

**Issue by MichalBryxi** [winds-mobi/winds-mobi-providers#73]
- As of now _most_ of the stations around me show 9 days old data for `gxaircom.net`
- There is one station (that I know of) - "Hohwald" that seems to still show updated data for `gxaircom.net`
- For most of the non functional `gxaircom.net` stations, it seems like `windline.ch` took over
- Now I can see two sources for few stations (see grey arrows on the map)

![photo_2023-08-02 16 57 48](https://github.com/winds-mobi/winds-mobi-providers/assets/847473/190e04c9-267f-441f-b0ba-9b7bd06e8a88)
![photo_2023-08-02 16 57 51](https://github.com/winds-mobi/winds-mobi-providers/assets/847473/ef79c228-7f64-494f-a2e7-bfc86c0c62a4)

**Comment by gereic** [comment]
@ysavary I'm sorry.
I was testing to bring some stations to windy with an OGN-Interface.
All Windline-stations where imported and I saw that windline already sends it stations to winds.mobi.

Can you please delete all GxAircomstations beginning with begins with 05 ?

Thank you.

**Comment by ysavary** [comment]
Hi @gereic,

I deleted the gxaircom stations starting with 05.

But it looks like that gxaircom republishes data from providers meteoswiss and holfuy too. The gxaircom timestamp does not match the data timestamp published by the provider as shown in the screenshots below. Moreover, it's weird, because it appears that the wind values are slightly modified.

Meteoswiss interlaken at 9h53:
![Screenshot 2023-08-08 at 09 53 15](https://github.com/winds-mobi/winds-mobi-providers/assets/600094/e4d6fea7-92f1-4999-9680-1e8dcf01a912)

Holfuy interlaken:
![Screenshot 2023-08-08 at 09 29 51](https://github.com/winds-mobi/winds-mobi-providers/assets/600094/a8bc1e3c-d332-4c49-b1f4-7edaf9cac8dd)

**Comment by MichalBryxi** [comment]
From the area of my interest I still have one duplicate:

![Screenshot 2023-08-08 at 14 50 04](https://github.com/winds-mobi/winds-mobi-providers/assets/847473/7e5cb732-0a13-4e35-bb65-3337ecee1052)

- Dead: Höhematte - windline.ch
- Alive: Höhematte holfuy - holfuy.com

The name "Höhematte holfuy" seems a bit meh as it seems like the provider just appended their name behind the name of the location for some reason.

**Comment by gereic** [comment]
@ysavary you are right.
Can you delete the gxaircom-stations which starts with FC ?
Thanks.

**Comment by ysavary** [comment]
@gereic

> Is it ok, to forward skytraxx and burnair-stations from OGN

Yes, it would be awesome to have new stations in winds.mobi!

Burnair is already [consuming winds.mobi api](https://reports.winds.mobi/fanet.ch.html). I assume they repost the winds.mobi data on the FANET+ network, but not having a skytraxx myself, I'm not sure what they do with the winds.mobi data.

What are skytraxx and burnair stations?

**Comment by ysavary** [comment]
@MichalBryxi 

"Dead: Höhematte - windline.ch" and "Alive: Höhematte holfuy - holfuy.com" are not really duplicate stations in the sense that they are 2 different stations and not exactly in the same place.

The name "Höhematte holfuy" was set by the admin of this [holfuy station](https://holfuy.com/fr/weather/1804). Winds.mobi uses the name of the station of the provider when it exists. This station was registered in holfuy.com by https://vkpi.ch. chilloutparagliding.com recently contacted me about this station. You should contact them if you would like to discuss the name they put.

**Comment by MichalBryxi** [comment]
@ysavary cool, thanks for explanation.

The dead "Höhematte - windline.ch" really [seems dead](https://m.windline.ch/meteodata.php?stationID=4117). I'm not sure what the cause might be and if I should annoy windline to fix it? Or if that is physically damaged device ... in which case not sure who can fix it?

Sorry if that's not your business, I will also try to contact chillout as they do a lot around here. Trying to make the map around here readable again :)

**Comment by MichalBryxi** [comment]
Ok, maybe one more to this topic to cover all the cases of gxaircom I can see. Just scrolled up and noticed that "Hohwald" still exists from gxaircom.net (and is dead). The arrows are not _exactly_ overlapping, but I don't think those will be two physically different stations. Can check it in person later if you want.

![Screenshot 2023-08-10 at 07 21 39](https://github.com/winds-mobi/winds-mobi-providers/assets/847473/a99e9470-45d1-4c5e-901a-17100df4b362)

**Comment by MichalBryxi** [comment]
Ok so few updates:

### Höhematte
Turns out there is a person behind the currently defunct station at *Höhematte* and from what he wrote that one should eventually be working again:

> if he means the gxaircom.net stations, i have no influence there. there is only howald at the moment. double. höhenmatte will have two working ones, one of them is in repair.

So I guess this "extra" one is actually ok.

### Hohwald
Got visual confirmation from a friend that went to Hohwald today that there is only one weather station there.

From the previous conversation on this ticket it seems like you deleted some old instances from the gxaricom.net source. I don't understand what [their page is saying](http://www.gxaircom.net/gxaircom/stationstable.php), but I can't find Hohwald there anymore.

So to me it seems like "Hohwald from gxaircom.net" can be deleted?
